### ISSUE TITLE
10.04 ubuntu build issue

### ISSUE THREAD

**Issue by huhongbo** [bodgit/graphite-amqp-tools#14]
i use 10.04 cmake 2.8.8 ,when compiling ,i got the error
-- checking for module 'librabbitmq>=0.2.0'
--   package 'librabbitmq>=0.2.0' not found

I think i have install the librabbitmq ,so i modify the CMakeLists.txt
pkg_check_modules(RABBITMQ REQUIRED librabbitmq)
to not check the version
-- checking for module 'librabbitmq'
--   found librabbitmq, version 0.2

It success ......
so the version check is the problem

**Comment by bodgit** [comment]
Interesting, given I would consider "0.2.0" and "0.2" to be the same version. I have a report of it building fine on 12.04 without needing any sort of modification.

Do you have the ".pc" file for librabbitmq installed? What does "pkg-config --libs librabbitmq" return?

**Comment by bodgit** [comment]
I'm sure when I was searching for cmake tips I read something about a bug in earlier versions with version number comparisons. Have you maybe got an older version of cmake installed still?

**Comment by huhongbo** [comment]
pkg-config --libs librabbitmq return 
-L/usr/local/lib -lrabbitmq

**Comment by bodgit** [comment]
The changes from #17 have set the version to "0.2" so this should fix the issue for now but I think there is a bug lurking to do with cmake/pkgconfig and parsing/comparing version numbers as "0.2" and "0.2.0" are semantically the same version in my opinion.

**Comment by cameronbraid** [comment]
Where did you get librabbitmq v 0.2 for ubuntu ?

**Comment by bodgit** [comment]
I suspect you'll need to roll your own from https://github.com/alanxz/rabbitmq-c although I note there's a version 0.3(.0) now. I (semi-)maintain some RPM's for CentOS/RHEL 5/6 but I don't know who does similar for Ubuntu.
