### ISSUE TITLE
graphite metrics

### ISSUE THREAD

**Issue by davewongillies** [bodgit/graphite-amqp-tools#15]
It'd be nice if graphite-{enqueue,dequeue} could send some metrics to graphite such as:
- number of messages sent/received
- bytes transferred/received
- number of parse errors

It'd probably need to be have set in a config file:
- graphite host
- interval
- metric prefix

**Comment by bodgit** [comment]
Yes, I was thinking about adding something like this. For graphite-enqueue this is fairly easy as it's using libevent for the event loop, just set a timer to fire every interval. For graphite-dequeue this is not so trivial as it basically sits blocking on librabbitmq.

What I ideally need is a non-blocking AMQP library, or to see if I can throw threads at the problem, which I'm hesitant to do as it just brings its own set of headaches.

I'll definitely see what I can do.
